//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.08 at 11:56:15 PM BRT 
//


package br.inf.portalfiscal.nfe;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.inf.portalfiscal.nfe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RetDPEC_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "retDPEC");
    private final static QName _EnvDPEC_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "envDPEC");
    private final static QName _ConsDPEC_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "consDPEC");
    private final static QName _RetConsDPEC_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "retConsDPEC");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.inf.portalfiscal.nfe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TRetDPEC }
     * 
     */
    public TRetDPEC createTRetDPEC() {
        return new TRetDPEC();
    }

    /**
     * Create an instance of {@link TDPEC }
     * 
     */
    public TDPEC createTDPEC() {
        return new TDPEC();
    }

    /**
     * Create an instance of {@link TDPEC.InfDPEC }
     * 
     */
    public TDPEC.InfDPEC createTDPECInfDPEC() {
        return new TDPEC.InfDPEC();
    }

    /**
     * Create an instance of {@link TRetConsDPEC }
     * 
     */
    public TRetConsDPEC createTRetConsDPEC() {
        return new TRetConsDPEC();
    }

    /**
     * Create an instance of {@link TConsDPEC }
     * 
     */
    public TConsDPEC createTConsDPEC() {
        return new TConsDPEC();
    }

    /**
     * Create an instance of {@link TRetDPEC.InfDPECReg }
     * 
     */
    public TRetDPEC.InfDPECReg createTRetDPECInfDPECReg() {
        return new TRetDPEC.InfDPECReg();
    }

    /**
     * Create an instance of {@link TDPEC.InfDPEC.IdeDec }
     * 
     */
    public TDPEC.InfDPEC.IdeDec createTDPECInfDPECIdeDec() {
        return new TDPEC.InfDPEC.IdeDec();
    }

    /**
     * Create an instance of {@link TDPEC.InfDPEC.ResNFe }
     * 
     */
    public TDPEC.InfDPEC.ResNFe createTDPECInfDPECResNFe() {
        return new TDPEC.InfDPEC.ResNFe();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetDPEC }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "retDPEC")
    public JAXBElement<TRetDPEC> createRetDPEC(TRetDPEC value) {
        return new JAXBElement<TRetDPEC>(_RetDPEC_QNAME, TRetDPEC.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TDPEC }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "envDPEC")
    public JAXBElement<TDPEC> createEnvDPEC(TDPEC value) {
        return new JAXBElement<TDPEC>(_EnvDPEC_QNAME, TDPEC.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TConsDPEC }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "consDPEC")
    public JAXBElement<TConsDPEC> createConsDPEC(TConsDPEC value) {
        return new JAXBElement<TConsDPEC>(_ConsDPEC_QNAME, TConsDPEC.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetConsDPEC }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "retConsDPEC")
    public JAXBElement<TRetConsDPEC> createRetConsDPEC(TRetConsDPEC value) {
        return new JAXBElement<TRetConsDPEC>(_RetConsDPEC_QNAME, TRetConsDPEC.class, null, value);
    }

}
