//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.03 at 12:19:21 AM BRT 
//


package br.inf.portalfiscal.nfe;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.inf.portalfiscal.nfe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProcCancNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "procCancNFe");
    private final static QName _InutNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "inutNFe");
    private final static QName _RetConsSitNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "retConsSitNFe");
    private final static QName _ConsSitNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "consSitNFe");
    private final static QName _NFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "NFe");
    private final static QName _EnviNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "enviNFe");
    private final static QName _ConsStatServ_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "consStatServ");
    private final static QName _ConsReciNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "consReciNFe");
    private final static QName _RetInutNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "retInutNFe");
    private final static QName _NfeProc_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "nfeProc");
    private final static QName _RetConsReciNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "retConsReciNFe");
    private final static QName _CancNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "cancNFe");
    private final static QName _RetConsStatServ_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "retConsStatServ");
    private final static QName _RetConsCad_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "retConsCad");
    private final static QName _RetEnviNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "retEnviNFe");
    private final static QName _ProcInutNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "ProcInutNFe");
    private final static QName _ConsCad_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "ConsCad");
    private final static QName _RetCancNFe_QNAME = new QName("http://www.portalfiscal.inf.br/nfe", "retCancNFe");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.inf.portalfiscal.nfe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TProtNFe }
     * 
     */
    public TProtNFe createTProtNFe() {
        return new TProtNFe();
    }

    /**
     * Create an instance of {@link TRetEnviNFe }
     * 
     */
    public TRetEnviNFe createTRetEnviNFe() {
        return new TRetEnviNFe();
    }

    /**
     * Create an instance of {@link TRetConsCad }
     * 
     */
    public TRetConsCad createTRetConsCad() {
        return new TRetConsCad();
    }

    /**
     * Create an instance of {@link TRetConsCad.InfCons }
     * 
     */
    public TRetConsCad.InfCons createTRetConsCadInfCons() {
        return new TRetConsCad.InfCons();
    }

    /**
     * Create an instance of {@link TConsCad }
     * 
     */
    public TConsCad createTConsCad() {
        return new TConsCad();
    }

    /**
     * Create an instance of {@link TRetCancNFe }
     * 
     */
    public TRetCancNFe createTRetCancNFe() {
        return new TRetCancNFe();
    }

    /**
     * Create an instance of {@link TRetInutNFe }
     * 
     */
    public TRetInutNFe createTRetInutNFe() {
        return new TRetInutNFe();
    }

    /**
     * Create an instance of {@link TCancNFe }
     * 
     */
    public TCancNFe createTCancNFe() {
        return new TCancNFe();
    }

    /**
     * Create an instance of {@link TNFe }
     * 
     */
    public TNFe createTNFe() {
        return new TNFe();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe }
     * 
     */
    public TNFe.InfNFe createTNFeInfNFe() {
        return new TNFe.InfNFe();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Cana }
     * 
     */
    public TNFe.InfNFe.Cana createTNFeInfNFeCana() {
        return new TNFe.InfNFe.Cana();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.InfAdic }
     * 
     */
    public TNFe.InfNFe.InfAdic createTNFeInfNFeInfAdic() {
        return new TNFe.InfNFe.InfAdic();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Cobr }
     * 
     */
    public TNFe.InfNFe.Cobr createTNFeInfNFeCobr() {
        return new TNFe.InfNFe.Cobr();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Transp }
     * 
     */
    public TNFe.InfNFe.Transp createTNFeInfNFeTransp() {
        return new TNFe.InfNFe.Transp();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Transp.Vol }
     * 
     */
    public TNFe.InfNFe.Transp.Vol createTNFeInfNFeTranspVol() {
        return new TNFe.InfNFe.Transp.Vol();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Total }
     * 
     */
    public TNFe.InfNFe.Total createTNFeInfNFeTotal() {
        return new TNFe.InfNFe.Total();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det }
     * 
     */
    public TNFe.InfNFe.Det createTNFeInfNFeDet() {
        return new TNFe.InfNFe.Det();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto }
     * 
     */
    public TNFe.InfNFe.Det.Imposto createTNFeInfNFeDetImposto() {
        return new TNFe.InfNFe.Det.Imposto();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.COFINS }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.COFINS createTNFeInfNFeDetImpostoCOFINS() {
        return new TNFe.InfNFe.Det.Imposto.COFINS();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.PIS }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.PIS createTNFeInfNFeDetImpostoPIS() {
        return new TNFe.InfNFe.Det.Imposto.PIS();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.IPI }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.IPI createTNFeInfNFeDetImpostoIPI() {
        return new TNFe.InfNFe.Det.Imposto.IPI();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS createTNFeInfNFeDetImpostoICMS() {
        return new TNFe.InfNFe.Det.Imposto.ICMS();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Prod }
     * 
     */
    public TNFe.InfNFe.Det.Prod createTNFeInfNFeDetProd() {
        return new TNFe.InfNFe.Det.Prod();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Prod.Comb }
     * 
     */
    public TNFe.InfNFe.Det.Prod.Comb createTNFeInfNFeDetProdComb() {
        return new TNFe.InfNFe.Det.Prod.Comb();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Prod.DI }
     * 
     */
    public TNFe.InfNFe.Det.Prod.DI createTNFeInfNFeDetProdDI() {
        return new TNFe.InfNFe.Det.Prod.DI();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Ide }
     * 
     */
    public TNFe.InfNFe.Ide createTNFeInfNFeIde() {
        return new TNFe.InfNFe.Ide();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Ide.NFref }
     * 
     */
    public TNFe.InfNFe.Ide.NFref createTNFeInfNFeIdeNFref() {
        return new TNFe.InfNFe.Ide.NFref();
    }

    /**
     * Create an instance of {@link TInutNFe }
     * 
     */
    public TInutNFe createTInutNFe() {
        return new TInutNFe();
    }

    /**
     * Create an instance of {@link TConsSitNFe }
     * 
     */
    public TConsSitNFe createTConsSitNFe() {
        return new TConsSitNFe();
    }

    /**
     * Create an instance of {@link TProcCancNFe }
     * 
     */
    public TProcCancNFe createTProcCancNFe() {
        return new TProcCancNFe();
    }

    /**
     * Create an instance of {@link TRetConsSitNFe }
     * 
     */
    public TRetConsSitNFe createTRetConsSitNFe() {
        return new TRetConsSitNFe();
    }

    /**
     * Create an instance of {@link TEnviNFe }
     * 
     */
    public TEnviNFe createTEnviNFe() {
        return new TEnviNFe();
    }

    /**
     * Create an instance of {@link TRetConsReciNFe }
     * 
     */
    public TRetConsReciNFe createTRetConsReciNFe() {
        return new TRetConsReciNFe();
    }

    /**
     * Create an instance of {@link TRetConsStatServ }
     * 
     */
    public TRetConsStatServ createTRetConsStatServ() {
        return new TRetConsStatServ();
    }

    /**
     * Create an instance of {@link TNfeProc }
     * 
     */
    public TNfeProc createTNfeProc() {
        return new TNfeProc();
    }

    /**
     * Create an instance of {@link TConsStatServ }
     * 
     */
    public TConsStatServ createTConsStatServ() {
        return new TConsStatServ();
    }

    /**
     * Create an instance of {@link TConsReciNFe }
     * 
     */
    public TConsReciNFe createTConsReciNFe() {
        return new TConsReciNFe();
    }

    /**
     * Create an instance of {@link TProcInutNFe }
     * 
     */
    public TProcInutNFe createTProcInutNFe() {
        return new TProcInutNFe();
    }

    /**
     * Create an instance of {@link TVeiculo }
     * 
     */
    public TVeiculo createTVeiculo() {
        return new TVeiculo();
    }

    /**
     * Create an instance of {@link TEnderEmi }
     * 
     */
    public TEnderEmi createTEnderEmi() {
        return new TEnderEmi();
    }

    /**
     * Create an instance of {@link TEndereco }
     * 
     */
    public TEndereco createTEndereco() {
        return new TEndereco();
    }

    /**
     * Create an instance of {@link TLocal }
     * 
     */
    public TLocal createTLocal() {
        return new TLocal();
    }

    /**
     * Create an instance of {@link TProtNFe.InfProt }
     * 
     */
    public TProtNFe.InfProt createTProtNFeInfProt() {
        return new TProtNFe.InfProt();
    }

    /**
     * Create an instance of {@link TRetEnviNFe.InfRec }
     * 
     */
    public TRetEnviNFe.InfRec createTRetEnviNFeInfRec() {
        return new TRetEnviNFe.InfRec();
    }

    /**
     * Create an instance of {@link TRetConsCad.InfCons.InfCad }
     * 
     */
    public TRetConsCad.InfCons.InfCad createTRetConsCadInfConsInfCad() {
        return new TRetConsCad.InfCons.InfCad();
    }

    /**
     * Create an instance of {@link TConsCad.InfCons }
     * 
     */
    public TConsCad.InfCons createTConsCadInfCons() {
        return new TConsCad.InfCons();
    }

    /**
     * Create an instance of {@link TRetCancNFe.InfCanc }
     * 
     */
    public TRetCancNFe.InfCanc createTRetCancNFeInfCanc() {
        return new TRetCancNFe.InfCanc();
    }

    /**
     * Create an instance of {@link TRetInutNFe.InfInut }
     * 
     */
    public TRetInutNFe.InfInut createTRetInutNFeInfInut() {
        return new TRetInutNFe.InfInut();
    }

    /**
     * Create an instance of {@link TCancNFe.InfCanc }
     * 
     */
    public TCancNFe.InfCanc createTCancNFeInfCanc() {
        return new TCancNFe.InfCanc();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Emit }
     * 
     */
    public TNFe.InfNFe.Emit createTNFeInfNFeEmit() {
        return new TNFe.InfNFe.Emit();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Avulsa }
     * 
     */
    public TNFe.InfNFe.Avulsa createTNFeInfNFeAvulsa() {
        return new TNFe.InfNFe.Avulsa();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Dest }
     * 
     */
    public TNFe.InfNFe.Dest createTNFeInfNFeDest() {
        return new TNFe.InfNFe.Dest();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Exporta }
     * 
     */
    public TNFe.InfNFe.Exporta createTNFeInfNFeExporta() {
        return new TNFe.InfNFe.Exporta();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Compra }
     * 
     */
    public TNFe.InfNFe.Compra createTNFeInfNFeCompra() {
        return new TNFe.InfNFe.Compra();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Cana.ForDia }
     * 
     */
    public TNFe.InfNFe.Cana.ForDia createTNFeInfNFeCanaForDia() {
        return new TNFe.InfNFe.Cana.ForDia();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Cana.Deduc }
     * 
     */
    public TNFe.InfNFe.Cana.Deduc createTNFeInfNFeCanaDeduc() {
        return new TNFe.InfNFe.Cana.Deduc();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.InfAdic.ObsCont }
     * 
     */
    public TNFe.InfNFe.InfAdic.ObsCont createTNFeInfNFeInfAdicObsCont() {
        return new TNFe.InfNFe.InfAdic.ObsCont();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.InfAdic.ObsFisco }
     * 
     */
    public TNFe.InfNFe.InfAdic.ObsFisco createTNFeInfNFeInfAdicObsFisco() {
        return new TNFe.InfNFe.InfAdic.ObsFisco();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.InfAdic.ProcRef }
     * 
     */
    public TNFe.InfNFe.InfAdic.ProcRef createTNFeInfNFeInfAdicProcRef() {
        return new TNFe.InfNFe.InfAdic.ProcRef();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Cobr.Fat }
     * 
     */
    public TNFe.InfNFe.Cobr.Fat createTNFeInfNFeCobrFat() {
        return new TNFe.InfNFe.Cobr.Fat();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Cobr.Dup }
     * 
     */
    public TNFe.InfNFe.Cobr.Dup createTNFeInfNFeCobrDup() {
        return new TNFe.InfNFe.Cobr.Dup();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Transp.Transporta }
     * 
     */
    public TNFe.InfNFe.Transp.Transporta createTNFeInfNFeTranspTransporta() {
        return new TNFe.InfNFe.Transp.Transporta();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Transp.RetTransp }
     * 
     */
    public TNFe.InfNFe.Transp.RetTransp createTNFeInfNFeTranspRetTransp() {
        return new TNFe.InfNFe.Transp.RetTransp();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Transp.Vol.Lacres }
     * 
     */
    public TNFe.InfNFe.Transp.Vol.Lacres createTNFeInfNFeTranspVolLacres() {
        return new TNFe.InfNFe.Transp.Vol.Lacres();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Total.ICMSTot }
     * 
     */
    public TNFe.InfNFe.Total.ICMSTot createTNFeInfNFeTotalICMSTot() {
        return new TNFe.InfNFe.Total.ICMSTot();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Total.ISSQNtot }
     * 
     */
    public TNFe.InfNFe.Total.ISSQNtot createTNFeInfNFeTotalISSQNtot() {
        return new TNFe.InfNFe.Total.ISSQNtot();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Total.RetTrib }
     * 
     */
    public TNFe.InfNFe.Total.RetTrib createTNFeInfNFeTotalRetTrib() {
        return new TNFe.InfNFe.Total.RetTrib();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.II }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.II createTNFeInfNFeDetImpostoII() {
        return new TNFe.InfNFe.Det.Imposto.II();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ISSQN }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ISSQN createTNFeInfNFeDetImpostoISSQN() {
        return new TNFe.InfNFe.Det.Imposto.ISSQN();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.PISST }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.PISST createTNFeInfNFeDetImpostoPISST() {
        return new TNFe.InfNFe.Det.Imposto.PISST();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.COFINSST }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.COFINSST createTNFeInfNFeDetImpostoCOFINSST() {
        return new TNFe.InfNFe.Det.Imposto.COFINSST();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.COFINS.COFINSAliq }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.COFINS.COFINSAliq createTNFeInfNFeDetImpostoCOFINSCOFINSAliq() {
        return new TNFe.InfNFe.Det.Imposto.COFINS.COFINSAliq();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.COFINS.COFINSQtde }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.COFINS.COFINSQtde createTNFeInfNFeDetImpostoCOFINSCOFINSQtde() {
        return new TNFe.InfNFe.Det.Imposto.COFINS.COFINSQtde();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.COFINS.COFINSNT }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.COFINS.COFINSNT createTNFeInfNFeDetImpostoCOFINSCOFINSNT() {
        return new TNFe.InfNFe.Det.Imposto.COFINS.COFINSNT();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.COFINS.COFINSOutr }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.COFINS.COFINSOutr createTNFeInfNFeDetImpostoCOFINSCOFINSOutr() {
        return new TNFe.InfNFe.Det.Imposto.COFINS.COFINSOutr();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.PIS.PISAliq }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.PIS.PISAliq createTNFeInfNFeDetImpostoPISPISAliq() {
        return new TNFe.InfNFe.Det.Imposto.PIS.PISAliq();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.PIS.PISQtde }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.PIS.PISQtde createTNFeInfNFeDetImpostoPISPISQtde() {
        return new TNFe.InfNFe.Det.Imposto.PIS.PISQtde();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.PIS.PISNT }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.PIS.PISNT createTNFeInfNFeDetImpostoPISPISNT() {
        return new TNFe.InfNFe.Det.Imposto.PIS.PISNT();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.PIS.PISOutr }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.PIS.PISOutr createTNFeInfNFeDetImpostoPISPISOutr() {
        return new TNFe.InfNFe.Det.Imposto.PIS.PISOutr();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.IPI.IPITrib }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.IPI.IPITrib createTNFeInfNFeDetImpostoIPIIPITrib() {
        return new TNFe.InfNFe.Det.Imposto.IPI.IPITrib();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.IPI.IPINT }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.IPI.IPINT createTNFeInfNFeDetImpostoIPIIPINT() {
        return new TNFe.InfNFe.Det.Imposto.IPI.IPINT();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMS00 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMS00 createTNFeInfNFeDetImpostoICMSICMS00() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMS00();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMS10 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMS10 createTNFeInfNFeDetImpostoICMSICMS10() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMS10();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMS20 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMS20 createTNFeInfNFeDetImpostoICMSICMS20() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMS20();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMS30 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMS30 createTNFeInfNFeDetImpostoICMSICMS30() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMS30();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMS40 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMS40 createTNFeInfNFeDetImpostoICMSICMS40() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMS40();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMS51 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMS51 createTNFeInfNFeDetImpostoICMSICMS51() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMS51();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMS60 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMS60 createTNFeInfNFeDetImpostoICMSICMS60() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMS60();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMS70 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMS70 createTNFeInfNFeDetImpostoICMSICMS70() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMS70();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMS90 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMS90 createTNFeInfNFeDetImpostoICMSICMS90() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMS90();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMSPart }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMSPart createTNFeInfNFeDetImpostoICMSICMSPart() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMSPart();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMSST }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMSST createTNFeInfNFeDetImpostoICMSICMSST() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMSST();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101 createTNFeInfNFeDetImpostoICMSICMSSN101() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN101();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN102 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN102 createTNFeInfNFeDetImpostoICMSICMSSN102() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN102();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN201 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN201 createTNFeInfNFeDetImpostoICMSICMSSN201() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN201();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202 createTNFeInfNFeDetImpostoICMSICMSSN202() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN202();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN500 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN500 createTNFeInfNFeDetImpostoICMSICMSSN500() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN500();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 }
     * 
     */
    public TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900 createTNFeInfNFeDetImpostoICMSICMSSN900() {
        return new TNFe.InfNFe.Det.Imposto.ICMS.ICMSSN900();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Prod.VeicProd }
     * 
     */
    public TNFe.InfNFe.Det.Prod.VeicProd createTNFeInfNFeDetProdVeicProd() {
        return new TNFe.InfNFe.Det.Prod.VeicProd();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Prod.Med }
     * 
     */
    public TNFe.InfNFe.Det.Prod.Med createTNFeInfNFeDetProdMed() {
        return new TNFe.InfNFe.Det.Prod.Med();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Prod.Arma }
     * 
     */
    public TNFe.InfNFe.Det.Prod.Arma createTNFeInfNFeDetProdArma() {
        return new TNFe.InfNFe.Det.Prod.Arma();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Prod.Comb.CIDE }
     * 
     */
    public TNFe.InfNFe.Det.Prod.Comb.CIDE createTNFeInfNFeDetProdCombCIDE() {
        return new TNFe.InfNFe.Det.Prod.Comb.CIDE();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Det.Prod.DI.Adi }
     * 
     */
    public TNFe.InfNFe.Det.Prod.DI.Adi createTNFeInfNFeDetProdDIAdi() {
        return new TNFe.InfNFe.Det.Prod.DI.Adi();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Ide.NFref.RefNF }
     * 
     */
    public TNFe.InfNFe.Ide.NFref.RefNF createTNFeInfNFeIdeNFrefRefNF() {
        return new TNFe.InfNFe.Ide.NFref.RefNF();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Ide.NFref.RefNFP }
     * 
     */
    public TNFe.InfNFe.Ide.NFref.RefNFP createTNFeInfNFeIdeNFrefRefNFP() {
        return new TNFe.InfNFe.Ide.NFref.RefNFP();
    }

    /**
     * Create an instance of {@link TNFe.InfNFe.Ide.NFref.RefECF }
     * 
     */
    public TNFe.InfNFe.Ide.NFref.RefECF createTNFeInfNFeIdeNFrefRefECF() {
        return new TNFe.InfNFe.Ide.NFref.RefECF();
    }

    /**
     * Create an instance of {@link TInutNFe.InfInut }
     * 
     */
    public TInutNFe.InfInut createTInutNFeInfInut() {
        return new TInutNFe.InfInut();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProcCancNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "procCancNFe")
    public JAXBElement<TProcCancNFe> createProcCancNFe(TProcCancNFe value) {
        return new JAXBElement<TProcCancNFe>(_ProcCancNFe_QNAME, TProcCancNFe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInutNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "inutNFe")
    public JAXBElement<TInutNFe> createInutNFe(TInutNFe value) {
        return new JAXBElement<TInutNFe>(_InutNFe_QNAME, TInutNFe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetConsSitNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "retConsSitNFe")
    public JAXBElement<TRetConsSitNFe> createRetConsSitNFe(TRetConsSitNFe value) {
        return new JAXBElement<TRetConsSitNFe>(_RetConsSitNFe_QNAME, TRetConsSitNFe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TConsSitNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "consSitNFe")
    public JAXBElement<TConsSitNFe> createConsSitNFe(TConsSitNFe value) {
        return new JAXBElement<TConsSitNFe>(_ConsSitNFe_QNAME, TConsSitNFe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "NFe")
    public JAXBElement<TNFe> createNFe(TNFe value) {
        return new JAXBElement<TNFe>(_NFe_QNAME, TNFe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TEnviNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "enviNFe")
    public JAXBElement<TEnviNFe> createEnviNFe(TEnviNFe value) {
        return new JAXBElement<TEnviNFe>(_EnviNFe_QNAME, TEnviNFe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TConsStatServ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "consStatServ")
    public JAXBElement<TConsStatServ> createConsStatServ(TConsStatServ value) {
        return new JAXBElement<TConsStatServ>(_ConsStatServ_QNAME, TConsStatServ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TConsReciNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "consReciNFe")
    public JAXBElement<TConsReciNFe> createConsReciNFe(TConsReciNFe value) {
        return new JAXBElement<TConsReciNFe>(_ConsReciNFe_QNAME, TConsReciNFe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetInutNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "retInutNFe")
    public JAXBElement<TRetInutNFe> createRetInutNFe(TRetInutNFe value) {
        return new JAXBElement<TRetInutNFe>(_RetInutNFe_QNAME, TRetInutNFe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TNfeProc }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "nfeProc")
    public JAXBElement<TNfeProc> createNfeProc(TNfeProc value) {
        return new JAXBElement<TNfeProc>(_NfeProc_QNAME, TNfeProc.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetConsReciNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "retConsReciNFe")
    public JAXBElement<TRetConsReciNFe> createRetConsReciNFe(TRetConsReciNFe value) {
        return new JAXBElement<TRetConsReciNFe>(_RetConsReciNFe_QNAME, TRetConsReciNFe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCancNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "cancNFe")
    public JAXBElement<TCancNFe> createCancNFe(TCancNFe value) {
        return new JAXBElement<TCancNFe>(_CancNFe_QNAME, TCancNFe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetConsStatServ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "retConsStatServ")
    public JAXBElement<TRetConsStatServ> createRetConsStatServ(TRetConsStatServ value) {
        return new JAXBElement<TRetConsStatServ>(_RetConsStatServ_QNAME, TRetConsStatServ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetConsCad }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "retConsCad")
    public JAXBElement<TRetConsCad> createRetConsCad(TRetConsCad value) {
        return new JAXBElement<TRetConsCad>(_RetConsCad_QNAME, TRetConsCad.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetEnviNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "retEnviNFe")
    public JAXBElement<TRetEnviNFe> createRetEnviNFe(TRetEnviNFe value) {
        return new JAXBElement<TRetEnviNFe>(_RetEnviNFe_QNAME, TRetEnviNFe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProcInutNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "ProcInutNFe")
    public JAXBElement<TProcInutNFe> createProcInutNFe(TProcInutNFe value) {
        return new JAXBElement<TProcInutNFe>(_ProcInutNFe_QNAME, TProcInutNFe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TConsCad }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "ConsCad")
    public JAXBElement<TConsCad> createConsCad(TConsCad value) {
        return new JAXBElement<TConsCad>(_ConsCad_QNAME, TConsCad.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetCancNFe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/nfe", name = "retCancNFe")
    public JAXBElement<TRetCancNFe> createRetCancNFe(TRetCancNFe value) {
        return new JAXBElement<TRetCancNFe>(_RetCancNFe_QNAME, TRetCancNFe.class, null, value);
    }

}
